name: schedule
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dotenv: ^4.1.0
  uuid: ^4.0.0
  dart_frog: ^1.1.0
  intl: ^0.19.0
  postgres: ^2.6.2
  bcrypt: ^1.0.1
  dart_jsonwebtoken: ^3.0.0
  http: ^1.3.0
  jwt_decoder: ^2.0.1
  
dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^7.0.0
